### ISSUE TITLE
ReadCourses

### ISSUE THREAD

**Issue by samuelcohen75** [LosProfesoresDeDauphine/Teach-spreadsheets#11]
Lecture d’un fichier de saisie des vœux. (Bien entendu, la lecture doit fonctionner quel que soit le nombre d’onglets et de cours.) Utilise l’interface SpreadsheetReader et l’implémentation ODSReader (éventuellement étendues).

**Comment by Kantoki** [comment]
Hypothèse simplificatrice :
- On ne prend pas en compte les onglets "LSO" et "Apprentissage", car notre code vérifie que les onglets présentent une certaine norme spécifique. En effet, ces deux onglets n'ont pas les mêmes canevas (templates) que les principaux onglets (DE1, L3 Informatique, etc...).
