### ISSUE TITLE
WriteCourses

### ISSUE THREAD

**Issue by samuelcohen75** [LosProfesoresDeDauphine/Teach-spreadsheets#12]
Classe permettant d’écrire un fichier de saisie des vœux, non rempli, à partir d’une liste de cours. Le programme se base sur un modèle disponible dans le class path, qui reprend les deux premiers onglets du fichier exemple..

**Comment by tuannamdavaux** [comment]
Hypothèses simplificatrices : 
- Comme pour le ReadCourses, on ne considère que les feuilles qui suivent le canevas de "DE1". On écrit donc une année d'étude avec ce canevas.
- Les listes de cours qu'on écrit,  correspondent aux cours des deux semestres de la même année d'étude.
- On considère que la feuille que l'on veut écrire n'existe pas encore.
- On considère que le fichier de saisie des voeux est généré en entier.
